version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"